baseURL = "https://containersolutions.github.io/runbooks/"
languageCode = "en-us"
title = "Kookbooks"
theme = "hugo-primer"

enableGitInfo = "true"

[frontmatter]
date = [":git", "lastmod", "date", "publishDate"]
