baseURL = "https://containersolutions.github.io/runbooks/"
languageCode = "en-us"
title = "Runbooks"
theme = "hugo-primer"

disqusShortname = "runbooks"
enableGitInfo = "true"

googleAnalytics = "UA-53586058-2"

[frontmatter]
date = [":git", "lastmod", "date", "publishDate"]
