baseURL = "https://containersolutions.github.io/runbooks/"
languageCode = "en-us"
title = "Runbooks"
theme = "hugo-primer-cs"

disqusShortname = "runbooks"
enableGitInfo = "true"

googleAnalytics = "UA-53586058-2"

[params]
showFooterCredits = false

[frontmatter]
date = [":git", "lastmod", "date", "publishDate"]

[menu]

[[menu.main]]
name = "Nav Menu"
weight = 1
identifier = "navmenu"
url = "/"

[[menu.main]]
name = "Home"
parent = "navmenu"
weight = 2
identifier = "home"
url = "/"
permalink = "/"

[[menu.main]]
name = "Kubernetes"
parent = "navmenu"
weight = 3
identifier = "kubernetes"
url = "/posts/kubernetes/"
permalink = "/posts/kubernetes"

[[menu.main]]
name = "Python"
parent = "navmenu"
weight = 4
identifier = "python"
url = "/posts/python/"
permalink = "/posts/python"

[[menu.main]]
name = "General"
parent = "navmenu"
weight = 5
identifier = "general"
url = "/posts/general/"
permalink = "/posts/general"
