[build]
  publish = "public"
  command = "HUGO_BASEURL=$URL hugo"

[build.environment]
  HUGO_VERSION = "0.71.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo"

[context.branch-deploy]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo"
